### ISSUE TITLE
Non-existent fields in options.json

### ISSUE THREAD

**Issue by pedroarbs** [andremun/InstanceSpace#11]
**Describe the bug**
The function `trainIS.m` returns error due to "reference to non-existent field". It occurs first in line [310](https://github.com/andremun/InstanceSpace/blob/master/trainIS.m#L310), because of `opts.pilot`. File `options.json` does not contain any field named 'pilot' (nor 'cloister', nor 'pythia') in the new version.

**To Reproduce**
1. run `trainIS('path/to/workspace')`

**Screenshots**
```
-------------------------------------------------------------------------
-> Loading the data.
-------------------------------------------------------------------------
-> Calculating the binary measure of performance
-> An algorithm is good if its performace is within 5% of the best.
-> For 1% of the instances there is more than one best algorithm. Random selection is used to break ties.
=========================================================================
-> Auto-pre-processing.
=========================================================================
-> Removing extreme outliers from the feature values.
-> Auto-normalizing the data using Box-Cox and Z transformations.
-------------------------------------------------------------------------
-> Using the complete set of the instances.
=========================================================================
-> Calling PILOT to find the optimal projection.
=========================================================================
Reference to non-existent field 'pilot'.

Error in trainIS (line 310)
model.pilot = PILOT(model.data.X, model.data.Y, model.data.featlabels, opts.pilot);
```

**Desktop (please complete the following information):**
 - OS: macOS Big Sur
 - Matlab R2020a

**Comment by andremun** [comment]
Please check the latest version of `example.m` for all the required fields. I will update the `readme.md` file as soon as possible.
Regards

**Comment by pedroarbs** [comment]
@andremun, thanks for the suggestion. Just an addition, I noticed that the parallel computing toolbox is now required, and I had an error because I didn't have it installed. One thing to add in the documentation.

**Comment by andremun** [comment]
Thanks. Will be added soon.
