### ISSUE TITLE
ERROR IN PBLDR

### ISSUE THREAD

**Issue by neelofarhassan** [andremun/InstanceSpace#2]
**Describe the bug**
Error while generating footprints for graph coloring 2015. Error logs are:

Error using fminusub (line 16)
Objective function is undefined at initial point. Fminunc cannot continue.

Error in fminunc (line 446)
   [x,FVAL,GRAD,HESSIAN,EXITFLAG,OUTPUT] = fminusub(funfcn,x, ...

Error in PBLDR (line 33)
        [out.alpha(:,i),out.eoptim(i)] = fminunc(errorfcn, out.X0(:,i), ...

Error in matilda (line 269)
out.pbldr = PBLDR(X, Y, opts.pbldr);

Error in example (line 54)
    out = matilda(rootdir);

**Comment by andremun** [comment]
I was probably an issue with nans. I'm clossing this now.
