### ISSUE TITLE
Links broken

### ISSUE THREAD

**Issue by jendrikseipp** [andremun/InstanceSpace#3]
The following links in the README are broken:

* http://matilda.unimelb.edu.au/our-methodology
* https://matilda.unimelb.edu.au/matildadata/graph_coloring_problem/metadata.csv

**Comment by andremun** [comment]
Thanks. They should be fixed by now.

**Comment by jendrikseipp** [comment]
Thanks for looking into this. Unfortunately, https://matilda.unimelb.edu.au/matilda/matildadata/graph_coloring_problem/metadata.csv still gives me an error 404 page.
