### ISSUE TITLE
Error in SVM fitting step

### ISSUE THREAD

**Issue by jeffrey-chr** [andremun/InstanceSpace#7]
Option-setting script is
[is_knapsack_script.txt](https://github.com/andremun/InstanceSpace/files/3667483/is_knapsack_script.txt)
renamed to .txt so Github will accept it.

Should be the same knapsack metadata file you already have.

Error message:

> -> Fitting SVM prediction models. This may take a while...
    -> 1 out of 5 models have been fitted.
    -> 2 out of 5 models have been fitted.
    -> 3 out of 5 models have been fitted.
Warning: One or more folds do not contain points from all the groups. 
> In internal.stats.cvpartitionImpl>stra_kfoldcv (line 364)
  In internal.stats.cvpartitionImpl/rerandom (line 315)
  In internal.stats.cvpartitionInMemoryImpl (line 166)
  In cvpartition (line 175)
  In fitoracle (line 15)
  In trainIS (line 387)
  In is_knapsack_script (line 59) 
EOF:ERROR
Error using crossval>getFuncVal (line 509)
The size of outputs of function '@(xtr,ytr,xte,yte)confusionmat(yte,svmwrap(xtr,ytr,xte,out.paramgrid(j,:),weight(i),false))' should be
the same.
Error in crossval (line 381)
                funResult = getFuncVal(i, nData, cvp, data, funorStr, szFunResult);
Error in fitoracle (line 19)
        out.cvcmat(j,:,i) = sum(crossval(f, Z, Ybin(:,i),'partition', cp));%,...
Error in trainIS (line 387)
model.algosel = fitoracle(model.pbldr.Z, Ybin, 
Error in is_knapsack_script (line 59)
    out = trainIS(rootdir);

**Comment by andremun** [comment]
What happen is that for the third algorithm, there are too many 0s or 1s. Therefore, when it tried to make the partition, it was unable to get two classes, which resulted in the confusion matrix operation failing. This is a tricky issue, as I don't want to hack on the MATLAB functions. I will give it a thought and let you know what happens. However, have you tried with all the data, or just a portion?
Thanks

**Comment by jeffrey-chr** [comment]
opts.selvars.smallscaleflag is set to false and opts.footprint.PCTILE is set to 0.3 - I think that answers your question?
